server:
  port: 8765
spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://yulj:yulj@eureka1:8761/eureka/,http://yulj:yulj@eureka2:8760/eureka/
feign:
  hystrix:
    enabled: true