eureka:
  client:
    serviceUrl:
      defaultZone: http://yulj:yulj@eureka1:8761/eureka/,http://yulj:yulj@eureka2:8760/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign