spring:
  application:
    name: eurka-server
  profiles:
    active: eureka2
eureka:
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: true
    # 是否从eureka上获取注册信息
    fetch-registry: true
