server:
  port: 8763

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://yulj:yulj@eureka1:8761/eureka/,http://yulj:yulj@eureka2:8760/eureka/