eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8760/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://localhost:9411